sudo: false
os:
  - linux
  - osx
language: rust
rust:
  - nightly-2016-04-13
  - nightly-2016-04-20
  - nightly-2016-04-25
  - nightly
script:
  - cargo build --verbose
  - cargo build --release --verbose
